Update ddev.yml

diff --git a/.github/workflows/ddev.yml b/.github/workflows/ddev.yml
--- a/.github/workflows/ddev.yml
+++ b/.github/workflows/ddev.yml
@@ -18,9 +18,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout
 
+      # See https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/#debianubuntu
       - name: Install DDEV
         run: |
-          set -e
           sudo sh -c 'echo ""'
           sudo install -m 0755 -d /etc/apt/keyrings
           curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ddev.gpg > /dev/null
@@ -29,16 +29,28 @@ jobs:
           echo "deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null
           sudo sh -c 'echo ""'
           sudo apt update && sudo apt install -y ddev
+          if [ $? -ne 0 ]; then
+            echo "DDEV installation failed"
+            exit 1
+          fi
 
       - name: Install Starshot
         run: |
-          set -e
           ddev quick-start
-        if: ${{ success() }}
+          if [ $? -ne 0 ]; then
+            echo "Starshot installation failed"
+            exit 1
+          fi
 
       - name: Confirm that Starshot is running
         run: |
-          set -e
           ddev list -W
+          if [ $? -ne 0 ]; then
+            echo "DDEV list failed"
+            exit 1
+          fi
           curl --location --silent http://dxpr-cms.ddev.site/node/1 | grep "<title>"
-        if: ${{ success() }}
+          if [ $? -ne 0 ]; then
+            echo "Curl command failed"
+            exit 1
+          fi
