test

diff --git a/.github/workflows/sync-repo.yml b/.github/workflows/sync-repo.yml
--- a/.github/workflows/sync-repo.yml
+++ b/.github/workflows/sync-repo.yml
@@ -63,8 +63,43 @@ jobs:
             echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
           fi
 
+      - name: Extract Current Tag Name
+        id: extract-tag
+        run: |
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+            echo "Current tag name: $TAG_NAME"
+            echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Sync Branch to Target Repo
+        if: ${{ steps.check-config.outputs.skip == 'false' && steps.extract-branch.outputs.branch != '' }}
+        run: |
+          failed=false
+          FORCE_PUSH=${{ env.FORCE_PUSH }}
+          TARGET_REPO=${{ env.TARGET_REPO_URL }}
+          BRANCH_NAME="${{ steps.extract-branch.outputs.branch }}"  # The current branch name that triggered the push
+          
+          echo "Syncing branch: $BRANCH_NAME"
+          
+          # Ensure the branch is checked out
+          git checkout "$BRANCH_NAME" || git checkout -b "$BRANCH_NAME" origin/"$BRANCH_NAME"
+
+          if [ "$FORCE_PUSH" == "true" ]; then
+            git push --force "$TARGET_REPO_URL" "$branch"
+          else
+            if ! git push "$TARGET_REPO_URL" "$branch"; then
+              echo "Error: Failed to push branch $branch to the target repository"
+              failed=true
+            fi
+          fi
+
+          if [ "$failed" = true ]; then
+            exit 1
+          fi
+
       # - name: List All Branches
-      #   if: ${{ steps.check-config.outputs.skip == 'false' }}
+      #   if: ${{ steps.check-config.outputs.skip == 'false' }}A
       #   id: list-branches
       #   run: |
       #     git fetch --all --unshallow
