test

diff --git a/.github/workflows/sync-repo.yml b/.github/workflows/sync-repo.yml
--- a/.github/workflows/sync-repo.yml
+++ b/.github/workflows/sync-repo.yml
@@ -77,6 +77,7 @@ jobs:
           fi
 
       - name: Check if Branch is Allowed to Sync
+        if: ${{ steps.extract-branch.outputs.branch != '' }}
         id: check-branch
         run: |
           BRANCH_NAME="${{ steps.extract-branch.outputs.branch }}"
@@ -92,7 +93,6 @@ jobs:
             echo "Branch '$BRANCH_NAME' is allowed for syncing."
             echo "skip_sync=false" >> $GITHUB_OUTPUT
           fi
-
 
       - name: Sync Branch to Target Repo
         if: ${{ steps.check-config.outputs.skip == 'false' && steps.check-branch.outputs.skip_sync == 'false' &&  steps.extract-branch.outputs.branch != '' }}
@@ -124,39 +124,40 @@ jobs:
             exit 1
           fi
 
-        - name: Check if Tag is Allowed to Sync
-          id: check-tag
-          run: |
-            TAG_NAME="${{ steps.extract-tag.outputs.tag }}"
-            ALLOWED_TAGS="${{ env.ALLOWED_TAGS_TO_SYNC }}"
-            
-            echo "Current tag: $TAG_NAME"
-            echo "Allowed tags: $ALLOWED_TAGS"
-            
-            if [[ ",$ALLOWED_TAGS," != *",$TAG_NAME,"* ]]; then
-              echo "Tag '$TAG_NAME' is not in the allowed list for syncing."
-              echo "skip_sync=true" >> $GITHUB_OUTPUT
-            else
-              echo "Tag '$TAG_NAME' is allowed for syncing."
-              echo "skip_sync=false" >> $GITHUB_OUTPUT
-            fi
+      - name: Check if Tag is Allowed to Sync
+        if: ${{ steps.extract-tag.outputs.tag != '' }}
+        id: check-tag
+        run: |
+          TAG_NAME="${{ steps.extract-tag.outputs.tag }}"
+          ALLOWED_TAGS="${{ env.ALLOWED_TAGS_TO_SYNC }}"
+          
+          echo "Current tag: $TAG_NAME"
+          echo "Allowed tags: $ALLOWED_TAGS"
+          
+          if [[ ",$ALLOWED_TAGS," != *",$TAG_NAME,"* ]]; then
+            echo "Tag '$TAG_NAME' is not in the allowed list for syncing."
+            echo "skip_sync=true" >> $GITHUB_OUTPUT
+          else
+            echo "Tag '$TAG_NAME' is allowed for syncing."
+            echo "skip_sync=false" >> $GITHUB_OUTPUT
+          fi
 
-        - name: Sync Tag to Target Repo
-          if: ${{ steps.check-config.outputs.skip == 'false' && steps.check-tag.outputs.skip_sync == 'false' && steps.extract-tag.outputs.tag != '' }}
-          run: |
-            failed=false
-            TARGET_REPO_URL=${{ env.TARGET_REPO_URL }}
-            TAG_NAME="${{ steps.extract-tag.outputs.tag }}"  # The current tag name that triggered the push
+      - name: Sync Tag to Target Repo
+        if: ${{ steps.check-config.outputs.skip == 'false' && steps.check-tag.outputs.skip_sync == 'false' && steps.extract-tag.outputs.tag != '' }}
+        run: |
+          failed=false
+          TARGET_REPO_URL=${{ env.TARGET_REPO_URL }}
+          TAG_NAME="${{ steps.extract-tag.outputs.tag }}"  # The current tag name that triggered the push
 
-            echo "Syncing tag: $TAG_NAME"
-            git tag "$TAG_NAME" || echo "It's ok, tag $TAG_NAME already exists"
-            # allow forge push?, currently, it's not allowed
+          echo "Syncing tag: $TAG_NAME"
+          git tag "$TAG_NAME" || echo "It's ok, tag $TAG_NAME already exists"
+          # allow forge push?, currently, it's not allowed
 
-            if ! git push "$TARGET_REPO_URL" "$TAG_NAME"; then
-              failed=true
-            fi
+          if ! git push "$TARGET_REPO_URL" "$TAG_NAME"; then
+            failed=true
+          fi
 
-            if [ "$failed" = true ]; then
-              echo "Error: Failed to push tag $TAG_NAME to the target repository"
-              exit 1
-            fi
+          if [ "$failed" = true ]; then
+            echo "Error: Failed to push tag $TAG_NAME to the target repository"
+            exit 1
+          fi
